// Test generated by RoostGPT for test azure-golang-multifile using AI Type Azure Open AI and AI Model roost-gpt4-32k

package helper

import (
	"testing"
	"fmt"
)

// TestHelp_57bf0fe14f provides testing for the Help function.
func TestHelp_57bf0fe14f(t *testing.T) {
	var tests = []struct {
		a        int
		b        int
		expected int
	}{
		{1, 2, 3},
		{-1, -2, -3},
		{100, 200, 300},
		{0, 0, 0},
	}

	for _, tt := range tests {
		testname := fmt.Sprint(tt.a) + " + " + fmt.Sprint(tt.b)
		t.Run(testname, func(t *testing.T) {
			ans := Help(tt.a, tt.b)
			if ans != tt.expected {
				t.Errorf("got %d, want %d", ans, tt.expected)
			} else {
				t.Log("Success")
			}
		})
	}
}
