// Test generated by RoostGPT for test azure-golang-multifile using AI Type Azure Open AI and AI Model roost-gpt4-32k

package main

import "testing"

// help is a function that takes two integers and returns their sum
func help(a int, b int) int {
	return a + b
}

func TestHelp(t *testing.T) {
	result := help(1, 2)

    if result != 3 {
		t.Errorf("Expected result to be 3, but got %v", result)
    }
}
